### ISSUE TITLE
バグレポート: 知識作成でサムネイル画像アップロード状態が不明

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/vook_web_v3#54]
# 再現手順
- 知識作成でサムネイル画像アップロード状態が不明
- スクショにある知識・アップロード前・知識・アップロード後参照

# 期待される振る舞い
- スクショにある記事・アップロード前・記事・アップロード後参照にある状態を作る。
- アップロードされていない場合は、選択されていません、されている場合は、ファイル名、を表示するようにする。

# スクショ
## 知識・アップロード前
<img width="1440" alt="スクリーンショット 2023-06-10 19 21 46" src="https://github.com/atsushimemet/vook_web_v3/assets/25111665/c4ce5de4-7875-4ab4-9e6e-7cee074c1b8e">

## 知識・アップロード後
<img width="1440" alt="スクリーンショット 2023-06-10 19 22 17" src="https://github.com/atsushimemet/vook_web_v3/assets/25111665/8911b681-eba8-456e-a476-1aabe5f8f570">

## 記事・アップロード前
<img width="1440" alt="スクリーンショット 2023-06-10 19 23 04" src="https://github.com/atsushimemet/vook_web_v3/assets/25111665/bbca777c-0924-40e9-8aa7-7047a275133a">

## 記事・アップロード後
<img width="1440" alt="スクリーンショット 2023-06-10 19 23 11" src="https://github.com/atsushimemet/vook_web_v3/assets/25111665/2abc88dc-c7ef-4947-9b70-7dc09fffdc54">

# 環境
## ブラウザ
# 関連イシュー

**Comment by atsushimemet** [comment]
# Todo
- [ ] 知識と記事の差分を生み出しているファイルを見つける

**Comment by atsushimemet** [comment]
- 知識
  - https://github.com/atsushimemet/vook_web_v3/blob/main/app/views/knowledges/_form.html.erb
- 記事
  - https://github.com/atsushimemet/vook_web_v3/blob/main/app/views/magazines/_form.html.erb

**Comment by atsushimemet** [comment]
ローカル開発環境で修正作業を実施して、ブラウザで確認という作業を行いたい。

そのために、下記手順を実施したい。
- データベースを作成およびマイグレーション
- サーバーを起動

データベース作成時に下記エラーが出て、今日は止まっている。
~/Repository/Vook/vook_web_v3 (main=)$ rails db:create                                 
rails aborted!
ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
/Users/ozawaatsushi/Repository/Vook/vook_web_v3/config/environment.rb:5:in `<main>'

Caused by:
OpenSSL::Cipher::CipherError: 
/Users/ozawaatsushi/Repository/Vook/vook_web_v3/config/environment.rb:5:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
~/Repository/Vook/vook_web_v3 (main=)$

**Comment by atsushimemet** [comment]
database.ymlからproduction環境の記述を削除することで、create,migrateまで完了
サーバー起動で以下エラー
<img width="1440" alt="スクリーンショット 2023-06-11 0 32 09" src="https://github.com/atsushimemet/vook_web_v3/assets/25111665/c92da613-45dc-415e-9a97-b70aa140e68d">

**Comment by atsushimemet** [comment]
ローカルでサーバー起動ok
<img width="1440" alt="スクリーンショット 2023-06-11 0 59 34" src="https://github.com/atsushimemet/vook_web_v3/assets/25111665/b0f17538-571f-437d-9dd4-f691b0f74394">
